# Where is the REST API located
rest-api-url: http://localhost:7082

# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8080
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:7081/oauth/token
      userAuthorizationUri: http://localhost:7081/oauth/authorize
      clientId: rent-a-car-client-id
      clientSecret: rent-a-car-client-secret
    resource:
      userInfoUri: http://localhost:7082/person

spring:
  datasource:
    url: jdbc:postgresql://localhost/rent_a_car
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # See https://github.com/pgjdbc/pgjdbc/issues/1102
  thymeleaf:
    cache: false # Necessary for hot swapping (See https://docs.spring.io/spring-boot/docs/current/reference/html/howto-hotswapping.html)

logging:
    level:
      org.springframework.security: DEBUG