# Make the OAuth2 Resource Server available on the port given by Heroku
server:
  port: ${PORT}

# RemoteTokenServices configuration
security:
  oauth2:
    client:
      clientId: rent-a-car-client-id
      clientSecret: rent-a-car-client-secret
    resource:
      tokenInfoUri: https://rent-a-car-auth-server.herokuapp.com/oauth/check_token
